import BookImg from "../assets/img/book.png";

const books = [
  {
    id: 1,
    bookName: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    image: BookImg,
    price: "$52",
    star: "4 Star",
    favorite: false,
    year: 1954,
  },
  {
    id: 2,
    bookName: "Moby-Dick",
    author: "Herman Melville",
    image: BookImg,
    price: "$67",
    star: "4 Star",
    favorite: true,
    year: 1851,
  },
  {
    id: 3,
    bookName: "Brave New World",
    author: "Aldous Huxley",
    image: BookImg,
    price: "$72",
    star: "4 Star",
    favorite: false,
    year: 1932,
  },
  {
    id: 4,
    bookName: "To Kill a Mockingbird",
    author: "Harper Lee",
    image: BookImg,
    price: "$42",
    star: "4 Star",
    favorite: true,
    year: 1960,
  },
  {
    id:5,
    bookName: "1984",
    author: "George Orwell",
    image: BookImg,
    price: "$52",
    star: "4 Star",
    favorite: false,
    year: 1949,
  },
  {
    id: 6,
    bookName: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    image: BookImg,
    price: "$60",
    star: "4 Star",
    favorite: true,
    year: 1925,
  },
  {
    id: 7,
    bookName: "Pride and Prejudice",
    author: "Jane Austen",
    image: BookImg,
    price: "$72",
    star: "4 Star",
    favorite: false,
    year: 1813,
  },
  {
    id: 8,
    bookName: "The Catcher in the Rye",
    author: "J.D. Salinger",
    image: BookImg,
    price: "$14.75",
    star: "4 Star",
    favorite: true,
    year: 1951,
  },
  {
    id: 9,
    bookName: "The Hobbit",
    author: "J.R.R. Tolkien",
    image: BookImg,
    price: "$11.20",
    star: "4 Star",
    favorite: true,
    year: 1937,
  },
  {
    id: 10,
    bookName: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    image: BookImg,
    price: "$16.50",
    star: "4 Star",
    favorite: true,
    year: 1967,
  }
];

export default books;